export const mediaData = [
  {
    id: 1,
    image: "/placeholder.svg",
    date: "2023-05-15",
    category: "Technology",
    username: "techguru",
    tags: ["AI", "Machine Learning"],
    description: "An article about recent advancements in AI",
  },
  {
    id: 2,
    image: "/placeholder.svg",
    date: "2023-05-16",
    category: "Travel",
    username: "wanderlust",
    tags: ["Europe", "Budget Travel"],
    description: "Tips for budget-friendly European vacations",
  },
  {
    id: 3,
    image: "/placeholder.svg",
    date: "2023-05-17",
    category: "Food",
    username: "foodielove",
    tags: ["Recipes", "Vegan"],
    description: "Delicious vegan recipes for beginners",
  },
  {
    id: 4,
    image: "/placeholder.svg",
    date: "2023-05-18",
    category: "Technology",
    username: "codemaster",
    tags: ["JavaScript", "React"],
    description: "Advanced React hooks and their use cases",
  },
  {
    id: 5,
    image: "/placeholder.svg",
    date: "2023-05-19",
    category: "Health",
    username: "fitnessguru",
    tags: ["Workout", "Nutrition"],
    description: "Balancing diet and exercise for optimal health",
  },
  {
    id: 7,
    image: "/placeholder.svg",
    date: "2023-05-19",
    category: "Health",
    username: "fitnessguru",
    tags: ["Workout", "Nutrition"],
    description: "Balancing diet and exercise for optimal health",
  },
  {
    id: 8,
    image: "/placeholder.svg",
    date: "2023-05-19",
    category: "Health",
    username: "fitnessguru",
    tags: ["Workout", "Nutrition"],
    description: "Balancing diet and exercise for optimal health",
  },
  {
    id: 9,
    image: "/placeholder.svg",
    date: "2023-05-19",
    category: "Health",
    username: "fitnessguru",
    tags: ["Workout", "Nutrition"],
    description: "Balancing diet and exercise for optimal health",
  },
  {
    id: 10,
    image: "/placeholder.svg",
    date: "2023-05-19",
    category: "Health",
    username: "fitnessguru",
    tags: ["Workout", "Nutrition"],
    description: "Balancing diet and exercise for optimal health",
  },
  {
    id: 11,
    image: "/placeholder.svg",
    date: "2023-05-19",
    category: "Health",
    username: "fitnessguru",
    tags: ["Workout", "Nutrition"],
    description: "Balancing diet and exercise for optimal health",
  },
  {
    id: 12,
    image: "/placeholder.svg",
    date: "2023-05-19",
    category: "Health",
    username: "fitnessguru",
    tags: ["Workout", "Nutrition"],
    description: "Balancing diet and exercise for optimal health",
  },
];
